### ISSUE TITLE
linter-mypy generating many duplicate errors

### ISSUE THREAD

**Issue by Askaholic** [elarivie/linter-mypy#20] opened 2019-05-07 07:23 UTC
For some reason many of my mypy warnings show up multiple times. Any idea why this would be happening? I am using mypy in conjunction with the `linter-flake8` package.

![Imgur](https://i.imgur.com/EqmBiEv.png)

Atom: 1.33.1
OS: Ubuntu 18
Python: 3.6
Pip:
```
mypy==0.701
mypy-extensions==0.4.1
```

**Comment by elarivie** [comment] 2019-06-13 14:54
Hello @Askaholic 

I have seen similar behavior with other linter like for example "Flake8":

![image](https://user-images.githubusercontent.com/8286066/59441174-28db1c00-8dc6-11e9-9679-3a0bc6e26a28.png)

It may be related to the following bug https://github.com/steelbrain/linter/issues/1450 from the package "Linter" which describe a feature about filtering duplicate warnings.

But I think that the real root cause is some kind of memory leak or race condition within the "[linter](https://github.com/steelbrain/linter)" package where warnings which are no more needed are nevertheless kept in the list because a **Workaround:**  to remove duplicate lint warning is to close and re-open atom. This seems to reset the internal memory of the "Linter" package and duplicate/no more needed warnings disappear.

**Comment by elarivie** [comment] 2019-08-19 12:37
Bug not directly related to linter-mypy, closing this issue...

**Closed as completed by elarivie** 2019-08-19 12:37 UTC
